In [13]:
from sklearn.preprocessing import OneHotEncoder 
import numpy as np

#sample data 
data= np.array(["cat", "dog", "man", "woman"]) 
data= data.reshape(-1,1)    # resize into column vector 
# one hot encode 
encoder= OneHotEncoder(sparse_output=False)
onthot_encode= encoder.fit_transform(data)
print(onthot_encode)

''' 
output: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
'''

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
