### One Hot Encoder

In [13]:
from sklearn.preprocessing import OneHotEncoder 
import numpy as np

#sample data 
data= np.array(["cat", "dog", "man", "woman"]) 
data= data.reshape(-1,1)    # resize into column vector 
# one hot encode 
encoder= OneHotEncoder(sparse_output=False)
onthot_encode= encoder.fit_transform(data)
print(onthot_encode)

''' 
output: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
'''

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Bag of Words

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

# data 
data= [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
# transform data into a table where row is the dictionary 
#                                   column is the rearranged input sentence 
vectorizer= CountVectorizer()
data= vectorizer.fit_transform(data)
print(data.toarray())
print(vectorizer.get_feature_names_out())
''' 
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]
['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
'''

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]
['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


### TF-IDF Method 

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
data= [
    'This is John',
    'This is not John'
]
tfidf= TfidfVectorizer() 
# convert to tfidf values 
val= tfidf.fit_transform(data)
for word, value in zip(tfidf.get_feature_names_out(), tfidf.idf_):
    print(word, ": ", value)

''' output 
is :  1.0
john :  1.0
not :  1.4054651081081644
this :  1.0
'''

is :  1.0
john :  1.0
not :  1.4054651081081644
this :  1.0


' output \nis :  1.0\njohn :  1.0\nnot :  1.4054651081081644\nthis :  1.0\n'