### Implement the scaled dot product attention with Wq,Wk,Wv matrices 

Compute key, value, queue values --> compute attention score for each of the words to measure similarity/importance --> scale the attention score 

In [1]:
import torch 
import numpy as np 

In [2]:
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [10]:
x= inputs[1] 
d_in = inputs. shape[1]     # input dimension 
d_out= 2    # hidden dimension

In [11]:
torch.manual_seed(123)

W_query = torch.nn.Parameter(torch.rand(d_in, d_out))
W_key   = torch.nn.Parameter(torch.rand(d_in, d_out))
W_value = torch.nn.Parameter(torch.rand(d_in, d_out))   # weight matrices are vocab size x hidden dimension

In [12]:
query_2= x @ W_query 
key_2= x @ W_key 
value_2= x @W_value 

# output: 1 x 2 to get the value for query, key and value 
print(query_2)

tensor([0.4306, 1.4551], grad_fn=<SqueezeBackward4>)


In [ ]:
# for each input, we need the attention from other inputs of Wk, and Wv 
keys= inputs @ W_key 
values= inputs @ W_key  # dim: 6 x 2 
print (keys)
print (keys.shape)

# each row is the key/value of each word (including our current target word)

tensor([[0.3669, 0.7646],
        [0.4433, 1.1419],
        [0.4361, 1.1156],
        [0.2408, 0.6706],
        [0.1827, 0.3292],
        [0.3275, 0.9642]], grad_fn=<MmBackward0>)
torch.Size([6, 2])


**Computing the attention score**  
-  Each word has an attention score for every input word. For example, $\omega_{22}$ is the second word's key value given the target word is the 2nd word 
-  Compute the dot product between key (of non-input) and the query of input so we get the similarity between these 2 words 

In [ ]:
# sample for W22 

keys_2= keys[1] # retrive the key value for the second word 
attn_score_22 = query_2.dot(keys_2)
print(attn_score_22)

tensor(1.8524, grad_fn=<DotBackward0>)


We can compute this attention score between the input word and every other word in the input sentence 

In [15]:
attn_scores= query_2 @ keys.T 
print(attn_scores)

tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440],
       grad_fn=<SqueezeBackward4>)


Scaling the attention by dividing each term by d_k ** 0.5, so we avoid too large dot products that lead to very small gradients 

In [ ]:
d_k= keys.shape[-1] # column size= 2 
attn_weights= torch.softmax(attn_scores/ d_k **0.5, dim=-1)
print (attn_weights)    # 1x 6 

# the attention score for each word related to the input word because we multiplied this dot product with input word's query vector 

tensor([0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820],
       grad_fn=<SoftmaxBackward0>)


Compute the context vector to get the relative importance   
-  multiply the relative attention score with corresponding value block 

In [ ]:
context_vector= attn_weights @ values # dim: 1x 2 
print(context_vector)

tensor([0.3590, 0.9117], grad_fn=<SqueezeBackward4>)


We can extend this idea to a scaled dot product attention class where the operations are performed on each row. So instead of 1 x2 context vector for a single row(single input word), we'll have 6x2. Operations are done on each row.